name: CI

on: 
  push:
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  run-build:
    runs-on: windows-latest
    steps:
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dependencies
        run: |
          git submodule update --init --recursive;

      - name: Build
        run: |
          Remove-Item build -Recurse -Force -ErrorAction:SilentlyContinue -Confirm:$False | Out-Null;
          xmake build -y
